export default class CommonConst {
  static readonly IMAGE_RESOURCE: Resource[] = [
    $r('app.media.badge1'),
    $r('app.media.badge2'),
    $r('app.media.badge3'),
    $r('app.media.badge4'),
    $r('app.media.badge5'),
    $r('app.media.badge6')
  ];
  static readonly IMAGES_MIN: number = 3;
  static readonly ROTATE_ANGLE_360: number = 360;
  static readonly INIT_SCALE: number = 0.75;
  static readonly OFFSET_RADIUS: number = 145;
  static readonly ICON_WIDTH: number = 58;
  static readonly ICON_HEIGHT: number = 58;

  static readonly SCALE_RATIO: number = 1.25;
}